name = "fleet-app-api-dev"
main = "src/app.ts"
compatibility_date = "2022-12-10"

[vars]
ENVIRONMENT = "dev"
FRONTEND_URL = "http://localhost:3000"
API_URL = "http://localhost:8787"

[env.production]
name = "fleet-app-api"
ENVIRONMENT = "production"
FRONTEND_URL = "http://fleet-app.vercel.app"
API_URL = "https://fleet-app-api.yoiw-cw-demo.workers.dev"

[[ d1_databases ]]
binding = "DB"
database_name = "fleet-app"
database_id = "0063a8d1-24ad-4a2d-ad06-4e3bff2111aa"
preview_database_id = "3068b6aa-8108-4bb0-b624-4cb41e34a330"
